// tour-data.js
const tours = [
    {
        id: 1,
        title: "Hunza Valley Expedition",
        price: 899,
        duration: "7 days",
        groupSize: "12 max",
        destinations: "Hunza Valley",
        image: "images/pakistan/hunza.png",
        description: "7-day cultural and adventure tour through the majestic Hunza Valley with breathtaking mountain views and rich cultural experiences.",
        difficultyLevel: "Moderate",
        included: [
            "6 nights in 3-4 star hotels",
            "All meals (breakfast, lunch, dinner)",
            "Professional English-speaking guide",
            "All entrance fees and permits",
            "Private air-conditioned transport",
            "Domestic flight Gilgit-Islamabad"
        ],
        notIncluded: [
            "International flights",
            "Travel insurance",
            "Personal expenses",
            "Visa fees",
            "Tips for guides/drivers (recommended $5/day)"
        ],
        itinerary: [
            "Day 1: Arrival in Islamabad, orientation meeting",
            "Day 2: Fly to Gilgit (1hr), drive to Hunza (3hrs)",
            "Day 3: Altit & Baltit Forts, Karimabad exploration",
            "Day 4: Attabad Lake boat trip, Passu Cones",
            "Day 5: Khunjerab Pass day trip (China border)",
            "Day 6: Local village visit, cultural show",
            "Day 7: Return to Gilgit, fly to Islamabad"
        ],
        highlights: [
            "UNESCO-listed Baltit Fort",
            "Boat ride on turquoise Attabad Lake",
            "Panoramic views of Rakaposhi (7,788m)",
            "Traditional Wakhi culture experience",
            "Khunjerab National Park wildlife"
        ],
        accommodation: "3-4 star hotels with mountain views",
        transport: "Private Toyota Hiace/Sprinter, domestic flight",
        bestTime: "April to October",
        physicalRating: "3/5 (moderate walking)",
        ageRequirement: "Minimum 12 years",
        departurePoint: "Islamabad International Airport",
        returnPoint: "Islamabad International Airport",
        bookingDeadline: "30 days before departure",
        cancellationPolicy: "Full refund 60+ days prior, 50% 30-59 days, no refund <30 days",
        rating: 4.8,
        reviews: 47,
        guide: "Certified mountain guide + local cultural expert",
        insurance: "Not included (recommended)",
        visaRequirements: "Tourist visa required (we provide invitation letter)",
        dates: ["Apr 10-17", "May 5-12", "Jun 15-22", "Sep 1-8", "Oct 10-17"],
        category: "Adventure"
    },
    {
        id: 2,
        title: "Skardu & Shangrila",
        price: 1199,
        duration: "8 days",
        groupSize: "10 max",
        destinations: "Skardu, Shangrila, Kachura Lakes",
        image: "images/pakistan/skardu.jpg",
        description: "8-day journey to the gateway of the world's highest mountains with luxury lakeside stays.",
        difficultyLevel: "Moderate",
        included: [
            "7 nights accommodation (4-star in Skardu)",
            "All meals including 3 gourmet dinners",
            "Expert mountain guide",
            "All activities and entry fees",
            "Private 4x4 transport",
            "Satpara Lake cruise"
        ],
        notIncluded: ["International flights", "Personal gear", "Alcohol", "Visa fees"],
        itinerary: [
            "Day 1: Islamabad arrival",
            "Day 2: Fly to Skardu, Shangrila Resort",
            "Day 3: Kachura Lakes exploration",
            "Day 4: Satpara Lake & Fort",
            "Day 5: Deosai Plains day trip",
            "Day 6: Skardu Fort & local markets",
            "Day 7: Free day (optional trout fishing)",
            "Day 8: Return to Islamabad"
        ],
        highlights: [
            "Stay at famous Shangrila Resort",
            "Boat ride on 'Lower Kachura' (Heaven Lake)",
            "Wildlife spotting in Deosai National Park",
            "Visit 16th-century Skardu Fort",
            "Stargazing in pristine mountain air"
        ],
        accommodation: "4-star lakeview resorts + boutique hotels",
        transport: "Private 4x4 Land Cruisers + domestic flight",
        bestTime: "May to September",
        physicalRating: "2/5 (light to moderate)",
        ageRequirement: "Minimum 10 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "45 days (due to limited flights)",
        cancellationPolicy: "75% refund 60+ days, 25% 30-59 days, no refund <30 days",
        rating: 4.9,
        reviews: 32,
        guide: "Certified high-altitude guide",
        insurance: "Emergency evacuation included",
        visaRequirements: "Visa required (help available)",
        dates: ["May 15-23", "Jun 10-18", "Jul 5-13", "Aug 20-28", "Sep 10-18"],
        category: "Adventure"
    },
    {
        id: 3,
        title: "Swat Valley Explorer",
        price: 749,
        duration: "6 days",
        groupSize: "15 max",
        destinations: "Swat Valley",
        image: "images/pakistan/swat.jpg",
        description: "6-day tour of Pakistan's 'Switzerland' with lush valleys, ancient Buddhist sites, and rich cultural experiences.",
        difficultyLevel: "Easy",
        included: [
            "5 nights in 3-star hotels",
            "All breakfasts and 4 dinners",
            "Cultural guide",
            "All entry fees",
            "Private transport",
            "Mingora city tour"
        ],
        notIncluded: ["Lunches", "Personal expenses", "Travel insurance"],
        itinerary: [
            "Day 1: Arrival in Islamabad, drive to Swat (5hrs)",
            "Day 2: Mingora exploration, Buddhist ruins",
            "Day 3: Malam Jabba visit",
            "Day 4: Ushu Forest hike",
            "Day 5: Kalam Valley day trip",
            "Day 6: Return to Islamabad"
        ],
        highlights: [
            "Ancient Buddhist stupas and monasteries",
            "Malam Jabba ski resort views",
            "Ushu Forest nature walks",
            "Swat Museum artifacts",
            "Local handicraft markets"
        ],
        accommodation: "3-star valley-view hotels",
        transport: "Private air-conditioned vehicles",
        bestTime: "March to November",
        physicalRating: "2/5 (light walking)",
        ageRequirement: "All ages",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "15 days before departure",
        cancellationPolicy: "Full refund 30+ days prior, 50% 15-29 days, no refund <15 days",
        rating: 4.7,
        reviews: 38,
        guide: "Local Swat cultural guide",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Mar 5-11", "Apr 10-16", "May 15-21", "Sep 1-7", "Oct 10-16", "Nov 5-11"],
        category: "Adventure"
    },
    {
        id: 4,
        title: "Naran Kaghan Adventure",
        price: 699,
        duration: "5 days",
        groupSize: "12 max",
        destinations: "Naran, Kaghan, Saif-ul-Malook",
        image: "images/pakistan/naran.jpg",
        description: "5-day trip through the stunning Himalayan foothills featuring alpine lakes and majestic peaks.",
        difficultyLevel: "Moderate",
        included: [
            "4 nights in 3-star hotels/lodges",
            "All meals",
            "Mountain guide",
            "Jeep rides to high-altitude locations",
            "All park fees"
        ],
        notIncluded: ["Personal gear", "Travel insurance", "Islamabad hotel"],
        itinerary: [
            "Day 1: Islamabad to Naran (6hr drive)",
            "Day 2: Saif-ul-Malook Lake visit",
            "Day 3: Lalazar plateau excursion",
            "Day 4: Ansoo Lake hike",
            "Day 5: Return to Islamabad"
        ],
        highlights: [
            "Legendary Saif-ul-Malook Lake",
            "Lalazar 'flower meadows'",
            "Tear-shaped Ansoo Lake",
            "Kaghan Valley vistas",
            "Local folklore experiences"
        ],
        accommodation: "Mountain lodges and 3-star hotels",
        transport: "Private 4x4 Jeeps for high-altitude areas",
        bestTime: "June to September",
        physicalRating: "3/5 (some strenuous hiking)",
        ageRequirement: "Minimum 10 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "20 days before departure",
        cancellationPolicy: "Full refund 45+ days, 50% 20-44 days, no refund <20 days",
        rating: 4.6,
        reviews: 41,
        guide: "Local mountain guide",
        insurance: "Basic medical coverage included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Jun 1-6", "Jul 5-10", "Aug 10-15", "Sep 5-10"],
        category: "Adventure"
    },
    {
        id: 5,
        title: "Multan Cultural Tour",
        price: 599,
        duration: "4 days",
        groupSize: "15 max",
        destinations: "Multan",
        image: "images/pakistan/multan.jpg",
        description: "4-day exploration of the City of Saints, featuring Sufi shrines, ancient architecture, and vibrant bazaars.",
        difficultyLevel: "Easy",
        included: [
            "3 nights in 4-star hotel",
            "All breakfasts and 2 dinners",
            "Cultural guide",
            "All entry fees",
            "Private transport",
            "Blue pottery workshop"
        ],
        notIncluded: ["Lunches", "Personal shopping", "Camera fees at shrines"],
        itinerary: [
            "Day 1: Arrival in Multan, city orientation",
            "Day 2: Shrine tour (Shah Rukn-e-Alam, Bahauddin Zakariya)",
            "Day 3: Fort Kohna and old city walk",
            "Day 4: Departure"
        ],
        highlights: [
            "Iconic Sufi shrines",
            "Multan Fort history",
            "Blue pottery artisans",
            "Colorful bazaars",
            "Traditional Multani cuisine"
        ],
        accommodation: "4-star heritage-style hotel",
        transport: "Air-conditioned private van",
        bestTime: "October to March",
        physicalRating: "1/5 (light walking)",
        ageRequirement: "All ages",
        departurePoint: "Multan Airport",
        returnPoint: "Multan Airport",
        bookingDeadline: "10 days before departure",
        cancellationPolicy: "Full refund 20+ days prior, no refund <20 days",
        rating: 4.5,
        reviews: 29,
        guide: "Local Sufi culture expert",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Oct 5-9", "Nov 10-14", "Dec 1-5", "Jan 15-19", "Feb 10-14", "Mar 5-9"],
        category: "Historical"
    },
    {
        id: 6,
        title: "Mohenjo-Daro Discovery",
        price: 549,
        duration: "3 days",
        groupSize: "12 max",
        destinations: "Mohenjo-Daro",
        image: "images/pakistan/mohenjodaro.jpg",
        description: "3-day archaeological tour of the ancient Indus Valley civilization, a UNESCO World Heritage Site.",
        difficultyLevel: "Easy",
        included: [
            "2 nights in 3-star hotel",
            "All meals",
            "Archaeologist guide",
            "All entry fees",
            "Private transport",
            "Museum tour"
        ],
        notIncluded: ["Personal expenses", "Travel insurance"],
        itinerary: [
            "Day 1: Arrival in Larkana, transfer to site",
            "Day 2: Full day at Mohenjo-Daro ruins",
            "Day 3: Museum visit, departure"
        ],
        highlights: [
            "Great Bath structure",
            "Ancient drainage systems",
            "Priest-King statue",
            "Archaeological museum",
            "Dancing Girl artifact"
        ],
        accommodation: "Best available near site (3-star)",
        transport: "Air-conditioned private vehicle",
        bestTime: "November to February",
        physicalRating: "2/5 (site involves walking)",
        ageRequirement: "Minimum 8 years",
        departurePoint: "Larkana",
        returnPoint: "Larkana",
        bookingDeadline: "14 days before departure",
        cancellationPolicy: "Full refund 30+ days prior, 50% 14-29 days, no refund <14 days",
        rating: 4.4,
        reviews: 22,
        guide: "Trained archaeological guide",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Nov 5-8", "Dec 10-13", "Jan 15-18", "Feb 10-13"],
        category: "Historical"
    },
    {
        id: 7,
        title: "Fairy Meadows Trek",
        price: 1099,
        duration: "7 days",
        groupSize: "8 max",
        destinations: "Fairy Meadows, Nanga Parbat Base Camp",
        image: "images/pakistan/fairy-meadows.jpg",
        description: "7-day hiking adventure with breathtaking views of Nanga Parbat, the world's 9th highest mountain.",
        difficultyLevel: "Challenging",
        included: [
            "2 nights hotel, 4 nights camping",
            "All meals (camp meals prepared by chef)",
            "Mountain guide and porters",
            "Camping equipment (except sleeping bag)",
            "Jeep transport to trailhead",
            "National park fees"
        ],
        notIncluded: ["Personal trekking gear", "Travel insurance", "Islamabad hotel"],
        itinerary: [
            "Day 1: Arrival in Islamabad",
            "Day 2: Drive to Raikot Bridge (10hrs)",
            "Day 3: Jeep to Tato, trek to Fairy Meadows (3hrs)",
            "Day 4: Acclimatization day at Fairy Meadows",
            "Day 5: Trek to Nanga Parbat Base Camp (6hrs)",
            "Day 6: Return to Fairy Meadows",
            "Day 7: Return to Islamabad"
        ],
        highlights: [
            "Stunning views of Nanga Parbat (8,126m)",
            "Camping under starry skies",
            "Alpine meadows filled with wildflowers",
            "Views of Rakhiot Glacier",
            "Traditional mountain hospitality"
        ],
        accommodation: "Camping + basic mountain huts",
        transport: "Private 4x4 + trekking",
        bestTime: "June to September",
        physicalRating: "4/5 (good fitness required)",
        ageRequirement: "Minimum 16 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "60 days before departure",
        cancellationPolicy: "50% refund 90+ days, no refund <90 days",
        rating: 4.7,
        reviews: 35,
        guide: "Certified mountain guide (UIAA)",
        insurance: "Emergency evacuation included",
        visaRequirements: "Visa required",
        dates: ["Jun 1-8", "Jul 5-12", "Aug 10-17", "Sep 5-12"],
        category: "Adventure"
    },
    {
        id: 8,
        title: "Lahore Heritage Walk",
        price: 499,
        duration: "4 days",
        groupSize: "15 max",
        destinations: "Lahore",
        image: "images/pakistan/lahore.jpg",
        description: "4-day cultural immersion in Pakistan's culinary and historical capital, featuring Mughal architecture and vibrant food streets.",
        difficultyLevel: "Easy",
        included: [
            "3 nights in 4-star heritage hotel",
            "All breakfasts and 2 dinners",
            "Expert cultural guide",
            "All entry fees",
            "Private transport",
            "Food tour of Old Lahore"
        ],
        notIncluded: ["Lunches", "Personal shopping", "Optional activities"],
        itinerary: [
            "Day 1: Arrival, Lahore Fort and Badshahi Mosque",
            "Day 2: Walled City walking tour",
            "Day 3: Shalimar Gardens and food street",
            "Day 4: Departure"
        ],
        highlights: [
            "UNESCO-listed Lahore Fort",
            "Badshahi Mosque (one of world's largest)",
            "Wazir Khan Mosque tilework",
            "Heera Mandi cultural quarter",
            "Gourmet food street experience"
        ],
        accommodation: "Heritage boutique hotel",
        transport: "Private air-conditioned van + walking",
        bestTime: "Year-round",
        physicalRating: "2/5 (moderate walking)",
        ageRequirement: "All ages",
        departurePoint: "Lahore",
        returnPoint: "Lahore",
        bookingDeadline: "7 days before departure",
        cancellationPolicy: "Full refund 15+ days prior, no refund <15 days",
        rating: 4.8,
        reviews: 52,
        guide: "Local historian and food expert",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Jan 5-9", "Feb 10-14", "Mar 5-9", "Apr 10-14", "Oct 5-9", "Nov 10-14", "Dec 1-5"],
        category: "Historical"
    },
    {
        id: 9,
        title: "Chitral & Kalash Valleys",
        price: 949,
        duration: "6 days",
        groupSize: "10 max",
        destinations: "Chitral, Kalash Valleys",
        image: "images/pakistan/chitral.jpg",
        description: "6-day journey to meet the Kalash people and explore remote valleys with unique pagan traditions.",
        difficultyLevel: "Moderate",
        included: [
            "5 nights in local guesthouses",
            "All meals featuring local cuisine",
            "Cultural guide fluent in Kalasha",
            "All permits and entry fees",
            "Private 4x4 transport",
            "Traditional music performance"
        ],
        notIncluded: ["Personal gear", "Travel insurance", "Islamabad hotel"],
        itinerary: [
            "Day 1: Fly to Chitral from Islamabad",
            "Day 2: Explore Chitral town and fort",
            "Day 3: Drive to Bumburet Valley (Kalash)",
            "Day 4: Rumbur Valley exploration",
            "Day 5: Birir Valley visit",
            "Day 6: Return to Islamabad"
        ],
        highlights: [
            "Unique Kalash pagan culture",
            "Traditional Kalash festivals (if timing aligns)",
            "Chitral Fort history",
            "Hindu Kush mountain scenery",
            "Local handicraft workshops"
        ],
        accommodation: "Basic but clean guesthouses",
        transport: "Private 4x4 vehicles + domestic flight",
        bestTime: "May to October",
        physicalRating: "2/5 (light walking)",
        ageRequirement: "Minimum 12 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "30 days before departure",
        cancellationPolicy: "Full refund 45+ days prior, 50% 30-44 days, no refund <30 days",
        rating: 4.6,
        reviews: 28,
        guide: "Local Kalash culture expert",
        insurance: "Not included",
        visaRequirements: "Special permit required (we arrange)",
        dates: ["May 5-11", "Jun 10-16", "Jul 15-21", "Aug 20-26", "Sep 10-16", "Oct 5-11"],
        category: "Historical"
    },
    {
        id: 10,
        title: "Makran Coastal Highway",
        price: 1299,
        duration: "8 days",
        groupSize: "8 max",
        destinations: "Makran Coast, Gwadar, Ormara",
        image: "images/pakistan/makran.jpg",
        description: "8-day road trip along Pakistan's stunning Arabian Sea coastline featuring pristine beaches and unique Baloch culture.",
        difficultyLevel: "Moderate",
        included: [
            "7 nights in beachfront hotels",
            "All meals featuring fresh seafood",
            "Local Baloch guide",
            "All activities and entry fees",
            "Private 4x4 transport",
            "Boat trip to Astola Island"
        ],
        notIncluded: ["International flights", "Personal gear", "Alcohol"],
        itinerary: [
            "Day 1: Arrival in Karachi",
            "Day 2: Drive to Ormara",
            "Day 3: Kund Malir beach exploration",
            "Day 4: Hingol National Park visit",
            "Day 5: Gwadar city tour",
            "Day 6: Astola Island day trip",
            "Day 7: Coastal villages exploration",
            "Day 8: Return to Karachi"
        ],
        highlights: [
            "Pristine beaches along Makran Coast",
            "Astola Island (Pakistan's largest offshore island)",
            "Hingol National Park mud volcanoes",
            "Gwadar deep sea port",
            "Traditional Baloch hospitality"
        ],
        accommodation: "Best available coastal hotels (3-4 star)",
        transport: "Private 4x4 Land Cruisers",
        bestTime: "October to April",
        physicalRating: "2/5 (light walking)",
        ageRequirement: "Minimum 12 years",
        departurePoint: "Karachi",
        returnPoint: "Karachi",
        bookingDeadline: "45 days before departure",
        cancellationPolicy: "75% refund 60+ days, 25% 30-59 days, no refund <30 days",
        rating: 4.5,
        reviews: 19,
        guide: "Local Baloch culture expert",
        insurance: "Basic medical coverage included",
        visaRequirements: "Special permit required for some areas (we arrange)",
        dates: ["Oct 5-13", "Nov 10-18", "Dec 1-9", "Jan 15-23", "Feb 10-18", "Mar 5-13", "Apr 10-18"],
        category: "Adventure"
    },
    {
        id: 11,
        title: "Taxila Archaeological Journey",
        price: 649,
        duration: "4 days",
        groupSize: "12 max",
        destinations: "Taxila",
        image: "images/pakistan/taxila.jpg",
        description: "4-day exploration of Gandhara civilization's ancient Buddhist ruins, a UNESCO World Heritage Site near Islamabad.",
        difficultyLevel: "Easy",
        included: [
            "3 nights in 4-star hotel",
            "All meals featuring local cuisine",
            "Archaeologist guide",
            "All entry fees and permits",
            "Private transport",
            "Museum tours"
        ],
        notIncluded: ["Personal expenses", "Travel insurance", "Optional activities"],
        itinerary: [
            "Day 1: Arrival in Islamabad, orientation",
            "Day 2: Taxila Museum and Sirkap city",
            "Day 3: Julian monastery and Dharmarajika stupa",
            "Day 4: Mohra Moradu and departure"
        ],
        highlights: [
            "Ancient Buddhist university ruins",
            "Gandhara art and sculptures",
            "2,000-year-old city planning",
            "Taxila Museum artifacts",
            "Buddhist stupa architecture"
        ],
        accommodation: "4-star hotel in Islamabad",
        transport: "Private air-conditioned van",
        bestTime: "September to April",
        physicalRating: "2/5 (light walking)",
        ageRequirement: "All ages",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "14 days before departure",
        cancellationPolicy: "Full refund 30+ days prior, 50% 14-29 days, no refund <14 days",
        rating: 4.3,
        reviews: 24,
        guide: "Gandhara civilization expert",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Sep 5-9", "Oct 10-14", "Nov 5-9", "Dec 10-14", "Jan 15-19", "Feb 10-14", "Mar 5-9", "Apr 10-14"],
        category: "Historical"
    },
    {
        id: 12,
        title: "Rohtas Fort Expedition",
        price: 549,
        duration: "3 days",
        groupSize: "10 max",
        destinations: "Rohtas Fort",
        image: "images/pakistan/rohtas.jpg",
        description: "3-day tour of Sher Shah Suri's unconquered 16th century fortress, one of South Asia's most impressive military structures.",
        difficultyLevel: "Moderate",
        included: [
            "2 nights in 3-star hotel",
            "All meals featuring local cuisine",
            "Expert historian guide",
            "All entry fees",
            "Private transport",
            "Fort exploration map"
        ],
        notIncluded: ["Personal expenses", "Travel insurance"],
        itinerary: [
            "Day 1: Arrival in Islamabad, drive to fort (3hrs)",
            "Day 2: Full day fort exploration",
            "Day 3: Return to Islamabad"
        ],
        highlights: [
            "Massive 4km fort walls",
            "12 monumental gates",
            "Haveli Man Singh palace",
            "Ancient water reservoirs",
            "Strategic military architecture"
        ],
        accommodation: "Best available near site (3-star)",
        transport: "Private air-conditioned vehicle",
        bestTime: "October to March",
        physicalRating: "3/5 (considerable walking)",
        ageRequirement: "Minimum 10 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "14 days before departure",
        cancellationPolicy: "Full refund 30+ days prior, 50% 14-29 days, no refund <14 days",
        rating: 4.2,
        reviews: 18,
        guide: "Military history specialist",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Oct 5-8", "Nov 10-13", "Dec 1-4", "Jan 15-18", "Feb 10-13", "Mar 5-8"],
        category: "Historical"
    },
    {
        id: 13,
        title: "Makli Necropolis Discovery",
        price: 699,
        duration: "5 days",
        groupSize: "12 max",
        destinations: "Thatta, Makli Necropolis",
        image: "images/pakistan/makli.jpg",
        description: "5-day tour of one of the world's largest funerary sites in Thatta, featuring stunning Islamic architecture from 14th-18th centuries.",
        difficultyLevel: "Easy",
        included: [
            "4 nights in 3-star hotel",
            "All meals featuring Sindhi cuisine",
            "Cultural guide",
            "All entry fees",
            "Private transport",
            "Thatta city tour"
        ],
        notIncluded: ["Personal expenses", "Travel insurance"],
        itinerary: [
            "Day 1: Arrival in Karachi",
            "Day 2: Drive to Thatta, Makli exploration",
            "Day 3: Detailed necropolis study",
            "Day 4: Shah Jahan Mosque and Keenjhar Lake",
            "Day 5: Return to Karachi"
        ],
        highlights: [
            "Over 500,000 graves across 10km²",
            "Stunning stone carvings",
            "Royal tombs of Samma, Arghun and Tarkhan rulers",
            "Shah Jahan Mosque tilework",
            "Keenjhar Lake boat ride"
        ],
        accommodation: "Best available in Thatta (3-star)",
        transport: "Private air-conditioned vehicle",
        bestTime: "November to February",
        physicalRating: "2/5 (light walking)",
        ageRequirement: "All ages",
        departurePoint: "Karachi",
        returnPoint: "Karachi",
        bookingDeadline: "20 days before departure",
        cancellationPolicy: "Full refund 30+ days prior, 50% 20-29 days, no refund <20 days",
        rating: 4.4,
        reviews: 16,
        guide: "Islamic art and architecture expert",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Nov 5-10", "Dec 10-15", "Jan 15-20", "Feb 10-15"],
        category: "Historical"
    },
    {
        id: 14,
        title: "Harappa Civilization Tour",
        price: 599,
        duration: "4 days",
        groupSize: "12 max",
        destinations: "Harappa",
        image: "images/pakistan/harappa.jpg",
        description: "4-day journey to the sister city of Mohenjo-Daro, exploring the lesser-known but equally impressive ruins of the Indus Valley Civilization.",
        difficultyLevel: "Easy",
        included: [
            "3 nights in 3-star hotel",
            "All meals featuring Punjabi cuisine",
            "Archaeologist guide",
            "All entry fees",
            "Private transport",
            "Museum tour"
        ],
        notIncluded: ["Personal expenses", "Travel insurance"],
        itinerary: [
            "Day 1: Arrival in Lahore",
            "Day 2: Drive to Harappa (4hrs), site exploration",
            "Day 3: Detailed site study and museum visit",
            "Day 4: Return to Lahore"
        ],
        highlights: [
            "Ancient granary and working platforms",
            "Cemetery H culture artifacts",
            "Harappa Museum collections",
            "Early Indus script examples",
            "Traditional brick architecture"
        ],
        accommodation: "Best available near site (3-star)",
        transport: "Private air-conditioned vehicle",
        bestTime: "October to April",
        physicalRating: "2/5 (light walking)",
        ageRequirement: "All ages",
        departurePoint: "Lahore",
        returnPoint: "Lahore",
        bookingDeadline: "14 days before departure",
        cancellationPolicy: "Full refund 30+ days prior, 50% 14-29 days, no refund <14 days",
        rating: 4.3,
        reviews: 15,
        guide: "Indus Valley civilization expert",
        insurance: "Not included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Oct 5-9", "Nov 10-14", "Dec 1-5", "Jan 15-19", "Feb 10-14", "Mar 5-9", "Apr 10-14"],
        category: "Historical"
    },
    {
        id: 15,
        title: "Cholistan Desert Forts",
        price: 799,
        duration: "6 days",
        groupSize: "10 max",
        destinations: "Derawar Fort, Bahawalpur",
        image: "images/pakistan/bahawalpur.jpg",
        description: "6-day exploration of Derawar and desert fortress network in Pakistan's Cholistan Desert, featuring stunning desert landscapes.",
        difficultyLevel: "Moderate",
        included: [
            "5 nights in 3-4 star hotels",
            "All meals featuring local cuisine",
            "Desert guide",
            "All entry fees",
            "Private 4x4 transport",
            "Camel safari experience"
        ],
        notIncluded: ["Personal gear", "Travel insurance"],
        itinerary: [
            "Day 1: Arrival in Bahawalpur",
            "Day 2: Derawar Fort exploration",
            "Day 3: Desert safari to Marot Fort",
            "Day 4: Mirgarh and Islamgarh Forts",
            "Day 5: Bahawalpur city tour",
            "Day 6: Departure"
        ],
        highlights: [
            "Iconic Derawar Fort with 40 bastions",
            "Traditional Cholistan camel safari",
            "Desert star gazing",
            "Noor Mahal Palace visit",
            "Local artisan workshops"
        ],
        accommodation: "3-4 star hotels + desert camp",
        transport: "Private 4x4 vehicles",
        bestTime: "November to March",
        physicalRating: "3/5 (moderate activities)",
        ageRequirement: "Minimum 12 years",
        departurePoint: "Bahawalpur",
        returnPoint: "Bahawalpur",
        bookingDeadline: "30 days before departure",
        cancellationPolicy: "Full refund 45+ days prior, 50% 30-44 days, no refund <30 days",
        rating: 4.5,
        reviews: 21,
        guide: "Local desert expert",
        insurance: "Basic medical coverage included",
        visaRequirements: "Visa required for international visitors",
        dates: ["Nov 5-11", "Dec 10-16", "Jan 15-21", "Feb 10-16", "Mar 5-11"],
        category: "Historical"
    },
    {
        id: 16,
        title: "K2 Base Camp Trek",
        price: 2499,
        duration: "14 days",
        groupSize: "6 max",
        destinations: "K2 Base Camp, Concordia",
        image: "images/pakistan/k2.jpg",
        description: "14-day challenging trek to the foot of the world's 2nd highest peak through the breathtaking Baltoro Glacier.",
        difficultyLevel: "Extreme",
        included: [
            "3 nights hotel, 10 nights camping",
            "All meals (high-energy camp meals)",
            "UIAA certified mountain guide",
            "All camping equipment (except personal gear)",
            "Porters for group equipment",
            "All permits and fees"
        ],
        notIncluded: ["Personal trekking gear", "Travel insurance", "Islamabad hotels"],
        itinerary: [
            "Day 1-2: Islamabad arrival and briefing",
            "Day 3: Fly to Skardu",
            "Day 4: Drive to Askole (last village)",
            "Day 5-7: Trek to Urdukas via Jhola and Paiju",
            "Day 8-9: Trek to Concordia (K2 views)",
            "Day 10: K2 Base Camp day trek",
            "Day 11-13: Return trek",
            "Day 14: Return to Islamabad"
        ],
        highlights: [
            "Close-up views of K2 (8,611m)",
            "Concordia - 'Throne Room of Mountain Gods'",
            "Baltoro Glacier traverse",
            "Views of 4 eight-thousanders",
            "Ultimate trekking challenge"
        ],
        accommodation: "Expedition-grade camping",
        transport: "Private 4x4 + trekking + domestic flight",
        bestTime: "June to August",
        physicalRating: "5/5 (excellent fitness required)",
        ageRequirement: "Minimum 18 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "90 days before departure",
        cancellationPolicy: "50% refund 120+ days, no refund <120 days",
        rating: 4.9,
        reviews: 27,
        guide: "UIAA certified high-altitude guide",
        insurance: "Emergency evacuation included",
        visaRequirements: "Special permit required (we arrange)",
        dates: ["Jun 1-15", "Jul 5-19", "Aug 10-24"],
        category: "Adventure"
    },
    {
        id: 17,
        title: "Deosai National Park Trek",
        price: 1299,
        duration: "8 days",
        groupSize: "8 max",
        destinations: "Deosai Plains, Sheosar Lake",
        image: "images/pakistan/deosai.jpg",
        description: "8-day hike through the 'Land of Giants' above 4,000m with wildlife encounters and alpine flowers.",
        difficultyLevel: "Challenging",
        included: [
            "7 nights camping (high-quality tents)",
            "All meals prepared by camp chef",
            "Professional mountain guide + support staff",
            "All camping equipment (except sleeping bag)",
            "Porters for group equipment",
            "National park fees"
        ],
        notIncluded: ["Personal gear", "Travel insurance", "Islamabad hotels"],
        itinerary: [
            "Day 1: Islamabad gear check",
            "Day 2: Drive to Skardu (10hrs)",
            "Day 3: Acclimatization day",
            "Day 4-7: Deosai Plains trekking",
            "Day 8: Return to Skardu"
        ],
        highlights: [
            "Spot endangered Himalayan brown bears",
            "Camp beside Sheosar Lake",
            "See rare Himalayan wildflowers",
            "Experience complete wilderness",
            "Night photography opportunities"
        ],
        accommodation: "Expedition-grade camping",
        transport: "Private 4x4 + trekking",
        bestTime: "July to September",
        physicalRating: "4/5 (good fitness required)",
        ageRequirement: "Minimum 16 years",
        departurePoint: "Islamabad",
        returnPoint: "Islamabad",
        bookingDeadline: "60 days (for permit processing)",
        cancellationPolicy: "50% refund 90+ days, no refund <90 days",
        rating: 4.7,
        reviews: 28,
        guide: "Wilderness First Responder certified",
        insurance: "Emergency evacuation included",
        visaRequirements: "Visa required",
        dates: ["Jul 1-9", "Aug 5-13", "Sep 10-18"],
        category: "Adventure",
        specialNotes: "Bear safety training provided"
    }
];


// Function to get tour by ID
function getTourById(id) {
    return tours.find(tour => tour.id === id);
}